### ISSUE TITLE
Add new patch for assessment screen

### ISSUE THREAD

**Issue by gitioe** [GridProtectionAlliance/openSPM#5]
~~SPM Patch Identifier - autogenerated field...~~
~~Eliminate Patch Title~~
~~Eliminate Work Arounds~~
~~Change "Not for Compliance" to "Vulnerability - No Patch Available"~~

Alarm Critical Business Days - replace this with a binary checkbox with title "Expedite Review"; have patches marked as such appear highlighed or otherwise indicated in the "Open Patches" screen
~~On Vendor Stated Impact, remove "Critical"~~

~~Display the autocaluated date of "Date Patch Released" + 35 days for evaluation date deadline~~

~~Add Version for Target Platform...~~

**Comment by wbernest** [comment]
No work is being done on this project anymore.
